### ISSUE TITLE
NPE on skin apply ProtocolLib

### ISSUE THREAD

**Issue by comonier** [games647/FastLogin#182]
https://hastebin.com/ameloramev.sql
https://hastebin.com/ocidoziqit.vbs
https://hastebin.com/fogekaluga.vbs
https://hastebin.com/pafazusere.vbs
[latest.log](https://github.com/games647/FastLogin/files/1385163/latest.log)
spigot latest build from:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/93e20b3652e42c34d30c306592aaec7fd3a41504

**Comment by games647** [comment]
Please follow the issue template. Especially I need your server startup log.

**Comment by comonier** [comment]
done

**Comment by games647** [comment]
I need your config too.

**Comment by comonier** [comment]
`autoRegister: false
secondAttemptCracked: true
switchMode: false
premiumUuid: true
nameChangeCheck: true
forwardSkin: true
premium-warning: true
ip-addresses: []
mojang-request-limit: 600
autoLogin: true
driver: org.sqlite.JDBC
database: '{pluginDir}/FastLogin.db'

# MySQL
#driver: com.mysql.jdbc.Driver
#host: localhost
#port: 3306
#database: fastlogin
#username: myUser
#password: myPassword`

**Comment by games647** [comment]
Could you please check if after the newest build, you still get your skin.

**Comment by comonier** [comment]
CraftBukkit version git-Spigot-93e20b3-b8f84f3 (MC: 1.12.2)
[ProtocolLib] Loading ProtocolLib v4.4.0-SNAPSHOT-b390
[SkinsRestorer] Loading SkinsRestorer v13.1.4
[AuthMe] Loading AuthMe v5.4-SNAPSHOT-b1821
[Vault] Enabling Vault v1.5.6-b49


so ... I did not detect any problems apparently in any function of the plugin, those who have the premium option enabled can log in normally. skins work. I only opened the ticket because every time a player logs an error message appears in the multi-line console. so I thought it was cool to report you to update the plugin without these error messages. or tell me what I should do to fix this.

**Comment by games647** [comment]
I think I now know the source of this issue. I tried to set the skin of cracked players, but those players don't have a skin downloaded during login. So if everything works and the error is gone this ticket could be marked as resolved (by closing it).

**Comment by comonier** [comment]
shoul i do something ?

**Comment by comonier** [comment]
sorry i did not understand what u means about "if everythink works" i need to setup some config ? to solve the problem ?

**Comment by games647** [comment]
Just update. I thought the error is gone. Is this wrong?

**Comment by comonier** [comment]
update what ? the last build on http://ci.xephi.fr/job/FastLogin/ is 778
i am on that

**Comment by comonier** [comment]
oh sorry i just saw that now ! wait i will try use that you have updated that 778 yesterday ?

**Comment by comonier** [comment]
with the same number of build ? 778 > to 778 > ?

**Comment by comonier** [comment]
>>>>>>>>>>>>>>>>> SOLVED <<<<<<<<<<<<<<<<

TY
